/*import React, { useState } from 'react';
import './App.css';


/* function Helloword(props){
  return (    
  <div>{props.mytext}</div>
  )
} */

/* class Helloword extends React.Component{
  state = {
    show: true
  }
  cambioEstado = () => {
    this.setState({show: !this.state.show}) //Forma de cambiar el estado entre True|False
  }
  render(){
    if (this.state.show === true){
      return (          
          <div>
            {this.props.mytext}<br></br>
            <button onClick = {this.cambioEstado}>Estado</button>
          </div>      
          
      )
    } else return (
      <div>
        <p>No hay elementos</p>
        <button onClick = {this.cambioEstado}>Estado</button>
      </div>
      
    )
  }
}

function App() {
  return (
    <div className="App">
      <h1 id="hello"><Helloword mytext = "Hola Ariel" /></h1>
      <h2><Helloword mytext = "Bienvenido a la casa"/></h2>
    </div>
  );
} */

/* const App = () =>
<div className = "App">
  <h1><div><Helloword/></div></h1> 
  <h1><div><Helloword/></div></h1>    FORMA DE CREAR CON CONSTANTE Y ARROW FUNCTION
</div> */
// export default App;